### ISSUE TITLE
Add: Task, Taskrun and PipelineResource CRUD

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#102]
if tekton is deployed we should be able to manipulate some of the objects quickly.

Let's add basic CRUD for Task, Taskrun and PipelineResource

**Comment by anatoliyfedorenko** [comment]
Getting the errors simular to this one. 
```
pkg/resources/task/create.go:44:72: cannot use &taskObject (type *"github.com/triggermesh/tm/vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1".Task) as type *"github.com/triggermesh/tm/vendor/github.com/knative/build-pipeline/pkg/apis/pipeline/v1alpha1".Task in argument to clientset.Tekton.TektonV1alpha1().Tasks(t.Namespace).Create
``` Will have to figure out why that happens...

**Comment by anatoliyfedorenko** [comment]
OK, so, one problem is that the code wants to go to github.com/knative/build-pipeline/ but this is 
 exactly the same as https://github.com/tektoncd/pipeline because build pipeline was renamed in tekton I guess ... 

When I removed `github.com/knative/build-pipeline` from vendor, these errors disappeared. but new ones appeared. Will work on them. Vendor is crazy here :( Or maybe I am doing something wrong.

**Comment by anatoliyfedorenko** [comment]
Fixed error related to vendor. But now build fails with `error: unable to create file vendor/github.com/google/go-containerregistry/pkg/v1/mutate/testdata/whiteout/.wh.foo.txt: Operation not permitted` which I cannot reproduce locally :(

**Comment by anatoliyfedorenko** [comment]
@sebgoa please, have a look. The question is should I mirror the Task, TaskRun and PipelineResources structs from Aktion project? Now I just included name and namespace in their models.

**Comment by anatoliyfedorenko** [comment]
https://github.com/triggermesh/tm/pull/113#event-2255053718 this closes this ticket
