### ISSUE TITLE
investigate how to push

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#126]
now that we support tekton, assuming that we are in a repo that is a git repo, we could have:

```
tm push
```

which would read the git remote and generate a Task for the build using that remote as a pipeline resource.

if it's not git remote than we fall back to `kontext` like source upload ...

**Comment by tzununbekov** [comment]
> and generate a Task for the build

meaning that the repository should contain some build scenario, like cloudbuild, right?

**Comment by sebgoa** [comment]
meaning that with `tm push` we should create a PipelineResource for that repo (assuming there is a remote defined), a Task to run `tm deploy` which will create the Tasks to build the image and create the service....then a TaskRun for the inital Push.

We could tie in the transceiver from Aktion so that builds get started on external git push. But let's go easy and try to get a one off deployment

**Comment by tzununbekov** [comment]
I want to give a try to "[github-third-party-source](https://github.com/triggermesh/github-third-party-source)" containersource that I prepared recently to track repository events - it may fit CLI tool usage case perfectly because it doesn't require any tokens (I didn't want to overburden CLI config with any extra tokens, especially from external services)

**Comment by tzununbekov** [comment]
Merged into master:
https://github.com/triggermesh/tm#deployment-pipelines
