### ISSUE TITLE
How to build image without deploying

### ISSUE THREAD

**Issue by rymonroe** [triggermesh/tm#140]
The AWS Lambda examples show how to build and deploy code in a single `tm` command. Is it possible to issue command to build and push image to registry without automatically deploying it? I would like to do this separately and so far have been unable to.

**Comment by tzununbekov** [comment]
Hi @rymonroe, 

you can update `tm` from the latest master and try to run taskrun creation:
 
```
tm deploy taskrun python-sample -f sample-function-dir/ --args HANDLER=handler.endpoint -t https://raw.githubusercontent.com/triggermesh/runtime-build-tasks/master/aws-lambda/python37-runtime.yaml
``` 
then you should list taskruns with `tm get taskruns` and get details of the one with "python-sample-" prefix: `tm get taskrun python-sample-<rand>`. There will be "IMAGE" build parameter with image URL (should be pull-able after taskrun "READY" state become "true"). If you want to use external image registry, taskrun creation command accepts `-s` parameter with secret name that you create with `tm set registry-auth foo` as described [here](https://github.com/triggermesh/tm#docker-registry).

This workflow may look a bit complicated since it was mainly used as service deployment internal process, but we can improve usability if there are usecases for it

**Comment by rymonroe** [comment]
Thanks @tzununbekov I'll give it a try, to clarify I'll need the latest TM from master and not v0.0.13

**Comment by sebgoa** [comment]
@tzununbekov  can you document this step by step in the README or another md file ?

thanks

**Comment by tzununbekov** [comment]
`--build-only` service deployment flag added and documented
Closing this issue, @rymonroe feel free to reopen it if you have any additional questions
