### ISSUE TITLE
tm deploy with nonexistent build template shows confusing message

### ISSUE THREAD

**Issue by solsson** [triggermesh/tm#64]
This isn't a blocker because it's relatively easy to guess the actual error, but in times of confusion ...

You get errors like `Buildtemplate knative-node10-runtimez: Get knative-node10-runtimez: unsupported protocol scheme ""` if the `--build-template` doesn't exist in the namespace.

**Comment by tzununbekov** [comment]
I think we need to improve CLI logging abilities so that we could:

1. by default show simple messages, like "buildtemplate not found" for described case, and full message ("unsupported protocol scheme") for debugging purpose
2. redirect output when we use CLI packages in backend to send events to frontend (already have this task)

So I wouldn't change current messages because they are basically shows underlying information which we'll need for debug mode, but start working on logging improvements in general.

**Comment by tzununbekov** [comment]
Will be tracked here: https://github.com/triggermesh/tm/issues/65
