### ISSUE TITLE
Application in Kubernetes don't starting due missing credentials from Gitlab

### ISSUE THREAD

**Issue by garciapd** [triggermesh/tm#68]
Hi,

I'm following the Gitlab tutorial to deploy a serverless application from Gitlab and everything looks fine until the last step, when it deploys the application in Kubernetes (in GCP) the pod is not starting due an error in the  **build-step-git-source** initial container.

The errors I'm getting are:
- Unexpected error running git [fetch --depth=1 --recurse-submodules=yes origin master]: exit status 128
- fatal: 'registry.gitlab.com/repository(it is ok but i deleted in the comment)' does not appear to be a git repository
- fatal: Could not read from remote repository.
- Please make sure you have the correct access rights and the repository exists

The repository exists, so i guess the credentials are not properly managed. I have seen in the Configuration in Kubernetes that there are service accounts created.

This is the deployment job in the pipeline:

deploy:
  stage: deploy
  image: gcr.io/triggermesh/tm:v0.0.8
  environment: production
  only:
    - master
  script:
    - echo "$CI_REGISTRY_IMAGE"
    - tm -n "$KUBE_NAMESPACE" --config "$KUBECONFIG" deploy service "$CI_PROJECT_NAME" --from-image "$CI_REGISTRY_IMAGE" --wait

Any idea please?

**Comment by sebgoa** [comment]
Hi @garciapd are you using a private gitlab repository ?

**Comment by DylanGriffith** [comment]
> fatal: 'registry.gitlab.com/repository(it is ok but i deleted in the comment)' does not appear to be a git repository

I find this error message strange. That URL looks to be the URL for a docker image in the registry but the error message is saying it is expecting to find a git repository there

**Comment by garciapd** [comment]
@sebgoa it is a private gitlab repository yes, I tried having this in the deployment  but no luck neither:

- tm -n "$KUBE_NAMESPACE" set registry-auth gitlab-registry --registry "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password "$CI_JOB_TOKEN"
- tm -n "$KUBE_NAMESPACE" --config "$KUBECONFIG" --registry-host "$CI_REGISTRY_IMAGE" deploy service "$CI_PROJECT_NAME" --from-image "$CI_REGISTRY_IMAGE" --wait

**Comment by garciapd** [comment]
@sebgoa it si a private repository yes

@DylanGriffith you are right it is strange, but it is what the output says, i'm going to destroy the cluster and create it again

**Comment by tzununbekov** [comment]
Hey @garciapd, thanks for report
While I'm working on fix for private projects you may try function deployment with public repository, it should work fine

**Comment by tzununbekov** [comment]
@garciapd we've fixed image pulling for private projects, you need to add following line before `deploy service` command in your .gitlab-ci.yml:
```
tm -n "$KUBE_NAMESPACE" --config "$KUBECONFIG" set registry-auth gitlab-registry --username "$CI_REGISTRY_USER" --password "$CI_JOB_TOKEN" --registry "$CI_REGISTRY"
```
Please let us know if it helped you

**Comment by garciapd** [comment]
@tzununbekov thanks! the pipeline worked :)

It is not creating any pod though, but i guess it is because other reason, I have to check deeper. 

I just say it here in case you found the same problem before, maybe due the autogeneration of the deployments for K8s, it is creating 0 pods and if i try to scale it up to 1 i get that message 

`Does not have minimum availability`

I have a fresh cluster running with 3 instances with enough resources, I'm taking a look.

**Comment by tzununbekov** [comment]
@garciapd if your pipeline succeeded, everything must be ready to use, including deployment and pods; scaling will be managed by knative and if there is no requests coming to your function, number of pods should be 0.
If function in your docker image listens to port 8080, you may try to access it via domain shown in `https://gitlab.com/<username>/<repository>/serverless/functions` page. Be aware of function cold start time - it may take few seconds to handle first request

**Comment by garciapd** [comment]
@tzununbekov it tries to start but there is a container called **user-container** under the deployment that cannot start due permissions to fetch the image from Gitlab.

`Back-off pulling image "registry.gitlab.com/.....`
` Cannot pull image '' from the registry.`

Do you think this is something related with the previous issue?

**Comment by tzununbekov** [comment]
@garciapd I think I know what it is. I'll try a fix and comment additionally about results

**Comment by garciapd** [comment]
@tzununbekov Ok thanks, I see the imagePullSecrets is on the deployment, and the secret is created under the namespace properly. 

I changed the tag to **latest** in case the problem was the version but got same results, unhautorized, hope it helps.

**Comment by tzununbekov** [comment]
so, the problem is that we use temporary token to authorize against gitlab registry for private projects: `CI_JOB_TOKEN` expires right after corresponding CI job finishes and if service after it's been scaled to zero tries to start again on different node, image pull operation with this token fails.

Since there is no permanent read-write token available which we could use in pipeline to work with private images, I had to separate tokens into two types:
1. permanent readonly token for pull operations - token named `gitlab-deploy-token` with `read_registry` scope must be created manually as described [here](https://docs.gitlab.com/ee/user/project/deploy_tokens/#creating-a-deploy-token)
2. temporary "push" token for image export operations - `CI_JOB_TOKEN` may be used for this purpose

`--pull` and `--push` bool flags now may be passed to `tm set registry-auth` command to specify which type of token should be created (not needed if only one token being used)  

@garciapd your service doesn't export any images, so you only need to create [gitlab-deploy-token](https://docs.gitlab.com/ee/user/project/deploy_tokens/#gitlab-deploy-token) and update `tm set registry-auth` command to use gitlab deploy token instead of job-specific token:
```
tm -n "$KUBE_NAMESPACE" --config "$KUBECONFIG" set registry-auth gitlab-registry --username "$CI_DEPLOY_USER" --password "$CI_DEPLOY_PASSWORD" --registry "$CI_REGISTRY" --pull
```
Please keep using `latest` tag for test purposes and let me know how it goes. Thanks!

**Comment by garciapd** [comment]
@tzununbekov it works! Thanks!
